version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD:postgres
    ports:
      - 5432:5432

  api:
    image: myapi
    build:
      context: .
      dockerfile: Dockerfile_API
    ports:
      - 8000:8000
