version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD:postgres
    ports:
      - 5432:5432
    volumes:
      - /home/nati_hd16/dashapp/pgdata:/var/lib/postgresql/data

  api:
    image: myapi
    build:
      context: .
      dockerfile: Dockerfile_API
    ports:
      - 8000:8000

  dapp:
    image: myapp
    build:
      context: .
      dockerfile: Dockerfile_APP
    ports:
      - 8050:8050
    environment:
      - mykey=${mykey}
